### ISSUE TITLE
Check flutter dependencies and cleanup unused dependencies

### ISSUE THREAD

**Issue by ewanas** [LeastAuthority/flutter_wormhole_gui#45]
@ewanas @bryanchriswhite  I used this dependency to resize mobile UI to fit desktop. We don't need it now because we have totally separate UI for desktop.

_Originally posted by @shareef-dweikat in https://github.com/LeastAuthority/flutter_wormhole_gui/pull/2#discussion_r764276637_

**Comment by shareef-dweikat** [comment]
Done https://github.com/LeastAuthority/flutter_wormhole_gui/pull/56
